enableImmutableInstalls: false

enableProgressBars: false

# nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

# pnpMode: "loose"

yarnPath: .yarn/releases/yarn-rc.js
