name: Master
on:
  pull_request:
    branches:
      -master
    types: [closed]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        yarn install --frozen-lockfile
        yarn build
